version: "3.8"
services:
    server:
        image: nginx:1.25-alpine
        ports:
            - "80:80"
            - "3000:3000"
            - "81:81"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web
            - api
            - cms
    mysql:
        image: mysql:8.0.34
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: docker-db
        volumes:
            - mysql-volume:/var/lib/mysql
    web:
        build: ./web
    api:
        build: ./api
        environment:
            - DATABASE_HOST=mysql
            - DATABASE_USER=root
            - DATABASE_PASSWORD=password
            - DATABASE_NAME=docker-db
            - DATABASE_PORT=3306
        depends_on:
            - mysql
    cms:
        build: ./cms
        environment:
            - DB_HOST=mysql
            - DB_CONNECTION=mysql
            - DB_USERNAME=root
            - DB_PASSWORD=password
            - DB_DATABASE=docker-db
            - DB_PORT=3306
        depends_on:
            -   mysql

volumes:
    mysql-volume: